{% set version = "2.2.1" %}

package:
  name: gsl
  version: {{ version }}

source:
  fn: gsl-{{ version }}.tar.gz                                              # [not win]
  url: http://ftpmirror.gnu.org/gsl/gsl-{{ version }}.tar.gz                # [not win]
  sha256: 13d23dc7b0824e1405f3f7e7d0776deee9b8f62c62860bf66e7852d402b8b024  # [not win]
  git_url: https://github.com/shadowwalkersb/gsl.git  # [win]
  git_tag: master                                     # [win]

build:
  number: 0

test:
  commands:
    - gsl-config --prefix
    #- conda inspect linkages -p $PREFIX gsl  # [not win]
    #- conda inspect objects -p $PREFIX gsl  # [osx]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0
  license_file: COPYING
  summary: 'GNU Scientific Library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
