{% set version = "2.7.1" %}

package:
  name: gsl
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gsl/gsl-{{ version }}.tar.gz
  sha256: dcb0fbd43048832b757ff9942691a8dd70026d5da0ff85601e52687f6deeb34b
  patches:
    # diff from source distribution to https://github.com/ampl/gsl/tree/v2.7.0
    - 0001-patch_cmake_for_windows.diff  # [win]
    # avoid "make check" error: https://savannah.gnu.org/bugs/?52927
    # - bessel_test.diff

build:
  number: 0
  run_exports:
    # tends to break at minor revs
    #    https://abi-laboratory.pro/index.php?view=timeline&l=gsl
    - {{ pin_subpackage("gsl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - cmake  # [win]
    - m2-patch  # [win]
    - make     # [not win]
    - libtool  # [not win]
  host:
    - openblas-devel {{ openblas }}  # [blas_implementation == 'openblas']
test:
  commands:
    - gsl-config --prefix  # [not win]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl.dll       exit 1   # [win]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GNU Scientific Library

extra:
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - ocefpaf
