travis:
  secure:
    BINSTAR_TOKEN: f6NudwIora1CHvmOj/6bZwBHp9u9JUvbv2DB+UbW2EpSX3zAyNVdojF9hQbr+yJhAb7D8keMcmJm06vieEenYjIyTaswF9aGrEe/BkdAHSTzB+de5j5p5/vTlpT9UvsNIE/71BhH72f48lUwumqRd87hDuMD/fGLTTY533w0gRA2fL3JRf368D8m/ksmtlNhMFK0v7/E3KR9Tp07crs+hdgES4ZvKiiFwF0A8EsaZCu3D6NWEiFezAW0pl/MdnBxyjq0Cqy7WI0rMCuY74BQyYHI4XNlwoc1G0vLJ7jTg0wO0fVy1p+JjRmKP4Hk0CjkjqLIVaij8/1Gzy2DGVcBLzJUd3iIHU5CjrF6ZDsylsgXFojG5P5SkkStOTncFhvvMddKlPvYkWO14ygkm7dJJGWgbjLYn+/imhuRb91nbeKd18Dpsu9obXxNJZ2mYNXzagYznhmAABCOdegsnDThBh6uqyTsPVgCa/MUvlEp99L92+8eGorP3qruzW3su+66DV+PEtE04LQRaL3u6Mtvym/r1vAz5ytu9n9dDlrhveT7Pyemq89kVxZcn/4QmJCcdBWME5RoHiWsG56E5MjxdrSxjfgu1HxyPpA9g7CQCiIRYqoviCeq8ghf8LwvRUynE834P5V1da+jVX8ShfLPNI+EJcPokNsnHfeQ8YH2SZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
